[ui]
hideTopBar = true
hideControlPanel = true

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
base = "light"

[server]
headless = true

[deprecation]
showPyplotGlobalUse = false
